package com.team2.jax.contract;

import javax.xml.bind.annotation.XmlRootElement;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBIndexHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

@XmlRootElement
@DynamoDBTable(tableName="Contract")
public class Contract {

	
    private String id;
    
    private String sender;
    
    private long senderTime;
    
    private String recipient;
    
    private long recipientTime;
    
    private String docRef;
    
    private String docName;
    
	/*
	 * SigA(h(doc)) in base64 format
	 */
    private String intermediateContract;
    
	/*
	 * SigB(SigA(h(doc))) in base64 format
	 */
    private String contract;
    
    private boolean completed;

    @DynamoDBHashKey(attributeName="Id")  
    @DynamoDBAutoGeneratedKey
	public String getId() {
		return id;
	}

	public void setId(String id) {
		this.id = id;
	}

	@DynamoDBAttribute(attributeName="Sender")
	public String getSender() {
		return sender;
	}

	public void setSender(String sender) {
		this.sender = sender;
	}

	
	@DynamoDBIndexHashKey(globalSecondaryIndexName="Receiver",attributeName="Recipient")
	public String getRecipient() {
		return recipient;
	}

	public void setRecipient(String recipient) {
		this.recipient = recipient;
	}

	@DynamoDBAttribute(attributeName="DocRef")
	public String getDocRef() {
		return docRef;
	}

	public void setDocRef(String docRef) {
		this.docRef = docRef;
	}

	@DynamoDBAttribute(attributeName="DocName")
	public String getDocName() {
		return docName;
	}

	public void setDocName(String docName) {
		this.docName = docName;
	}

	@DynamoDBAttribute(attributeName="IntermediateContract")
	public String getIntermediateContract() {
		return intermediateContract;
	}

	public void setIntermediateContract(String intermediateContract) {
		this.intermediateContract = intermediateContract;
	}

	@DynamoDBAttribute(attributeName="Contract")
	public String getContract() {
		return contract;
	}

	public void setContract(String contract) {
		this.contract = contract;
	}

	@DynamoDBAttribute(attributeName="Status")
	public boolean isCompleted() {
		return completed;
	}

	public void setCompleted(boolean completed) {
		this.completed = completed;
	}
	
    @DynamoDBAttribute(attributeName="SenderTime")
    public void setSenderTime(long senderTime){
    	this.senderTime=senderTime;
    }
    
    public long getSenderTime(){
    	return senderTime;
    }
    
    @DynamoDBAttribute(attributeName="RecipientTime")
    public void setRecipientTime(long recipientTime){
    	this.recipientTime=recipientTime;
    }
    public long getRecipientTime(){
    	return recipientTime;
    }
}
